### ISSUE TITLE
XPath

### ISSUE THREAD

**Issue by neu-rah** [snoyberg/xml#101]
Hi!

Is there any plan to add xpath parser?
I thought i could give it a try for my own purposes but saw that **anyName** was added on 1.5.0, wonder if this is heading to a xpath parser, if its the case i should not bother with my efforts.

**Comment by k0ral** [comment]
You probably want [Text.XML.Cursor][1], which is inspired from XPath.
The `anyName` function you mentioned (and the whole [Text.XML.Stream.Parse][2] module) is probably irrelevant in this case: it is meant to consume the XML document once and in-order, while XPath is about arbitrarily traversing an XML document.

[1]: https://hackage.haskell.org/package/xml-conduit-1.5.0/docs/Text-XML-Cursor.html
[2]: https://hackage.haskell.org/package/xml-conduit-1.5.0/docs/Text-XML-Stream-Parse.html

**Comment by neu-rah** [comment]
thank you
