### ISSUE TITLE
Why is there a preferred version blocking 1.5 on Hackage?

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/xml#106]
Question to @k0ral, who I assume is the one who put it there (unfortunately Hackage doesn't provide that information). Why is there a preferred version of `< 1.5` on Hackage? I ask because of https://github.com/fpco/stackage/issues/2312

**Comment by k0ral** [comment]
I set that preferred version following discussion [here][1].
I suppose we can lift it now, given that:
- it's been set for several months, which is reasonably long enough for reverse-dependencies' maintainers to upgrade to `xml-conduit` >1.5, according to deprecation warnings
- incompatibilities detected by stackage have been fixed (cf https://github.com/fpco/stackage/issues/2312#issuecomment-308694300)

What do you think ?

[1]: https://github.com/snoyberg/xml/pull/93#issuecomment-275208946

**Comment by snoyberg** [comment]
Yeah, I'd say go for it.

**Comment by k0ral** [comment]
Done.
