### ISSUE TITLE
innerText for stream parser

### ISSUE THREAD

**Issue by agrafix** [snoyberg/xml#107]
For a project I needed an `innerText` combinator that collects all text nodes from within a parent node. It looks like this:

https://github.com/agrafix/papergrep/blob/acbc47a9a99f8c255edd9597006b89bfef52c6e7/src/PG/Xml.hs#L82-L118

Is this an interesting contribution to have in `Text.XML.Stream.Parse` next to `content`?

**Comment by k0ral** [comment]
I believe `innerText` can be written as a composition of existing primitives:

```haskell
import Control.Lens.Prism (preview)
import Data.Conduit
import qualified Data.Conduit.Combinators as C
import qualified Text.XML.Stream.Parse as Xml

innerText = Xml.takeAnyTreeContent .| C.concatMap (preview _EventContentText) .| C.fold where
  _EventContentText = _ -- prism focusing on EventContent . ContentText
```

Can you confirm whether this meets your requirements ?
In case it does, I believe contributing prisms to `xml-types` would make more sense :) .

**Comment by agrafix** [comment]
Looks elegant, thanks! I'll try it out.

**Comment by k0ral** [comment]
Closing this issue as no code will be done. Please reopen it in case something's wrong with my suggestion above.
