### ISSUE TITLE
Breaking change in xml-conduit-1.7.1.1

### ISSUE THREAD

**Issue by bergmark** [snoyberg/xml#124]
xml-conduit-parse fails against xml-conduit 1.7.1.1 but not 1.7.0.1, no other stackage packages seem to be affected:

```
Data/Conduit/Parser/XML.hs:142:53: error:
    • Couldn't match expected type ‘Maybe a2 -> e2’
                  with actual type ‘Reexport.XmlException’
    • The function ‘Reexport.XmlException’ is applied to two arguments,
      but its type ‘String -> Reexport.XmlException’ has only one
      In the second argument of ‘($)’, namely
        ‘Reexport.XmlException "AttrParser.empty" Nothing’
      In the second argument of ‘($)’, namely
        ‘toException $ Reexport.XmlException "AttrParser.empty" Nothing’
```

Was this intentional?

Also pinging @k0ral, the xml-conduit-parse maintainer, i dropped xml-conduit-parse from nightly for now just to get a snapshot out.

**Comment by k0ral** [comment]
This is a mistake on my part, clearly not intended. I had uncommitted changes locally when I did `cabal build && cabal sdist && cabal upload`.
I've uploaded 1.7.1.2 with the correct code (aligned with this repository), which is backward compatible with 1.7.0.*, and deprecated 1.7.1.1.
I'm sorry for this.

**Comment by bergmark** [comment]
Ah i didn't realize you maintained xml-conduit as well :-)

Thanks for the fix! I've re-enabled it, please let us know if there are still issues with xml-conduit-parse in nightly @cdornan
