### ISSUE TITLE
html-conduit: Entity decoding in attributes in 1.3.1 cuts off after & #038;

### ISSUE THREAD

**Issue by myfreeweb** [snoyberg/xml#128]
Test started failing after stackage upgraded to 1.3.1: https://github.com/myfreeweb/microformats2-parser/issues/5

Basically in

```html
<a href="https://example.com?a=b&#038;c=d">link</a>
```

href gets decoded as `https://example.com?a=b` which is certainly not what I would expect.

**Comment by snoyberg** [comment]
I was unable to repro with https://github.com/snoyberg/xml/commit/a451a4892b0cf850e0438ae0988e40f817dbd245. Can you provide a reproducing test case against html-conduit?

**Comment by snoyberg** [comment]
Just a guess: is it possible that you had a workaround in place previously to deal with the lack of entity decoding in tagstream-conduit, and introducing this bugfix caused you to double-unescape the entities?

**Comment by myfreeweb** [comment]
Oh. Sorry, yeah, that's it.

**Comment by snoyberg** [comment]
No worries, it was the only workaround for this buggy behavior before.
