### ISSUE TITLE
MonadUnliftIO and MonadThrow

### ISSUE THREAD

**Issue by limick** [snoyberg/xml#130]
My understanding is that `MonadUnliftIO` replaces `MonadThrow`, among others. I am therefore trying to remove all uses of `MonadThrow` in a Yesod web app.
However, `sinkDoc` from `xml-conduit-1.8.0` still uses `MonadThrow`. Is this library simply not ready for `MonadUnliftIO`?
Is there a way for me to use `sinkDoc :: MonadThrow m => ParseSettings -> ConduitT ByteString o m Document` without introducing `MonadThrow` in all the callers?

**Comment by snoyberg** [comment]
There are still use cases where `MonadThrow` is useful, namely when you have a monadic action which can fail but doesn't necessarily perform `IO`. In an ideal world, `MonadThrow` might have been a superclass of `MonadIO`, but we're stuck with what we have.

A nice trick is that `IO` is an instance of both `MonadThrow` and `MonadUnliftIO`, so if you use `sinkDoc` in a monomorphic context you will fulfill both sets of typeclass constrants, and then throwing in a `liftIO` can generalize back up to `MonadIO`. You _may_ need to use `transPipe` to lift the action inside the `ConduitT`. All of this is a bit of a pain unfortunately.

**Comment by ygale** [comment]
Would it make sense to have a `*-compatible` library that provides orphan `MonadCatch/MonadThrow` instances for any `MonadUnlifIO` instance, using the `UnmentionablyUnsafeInstances` extension?

**Comment by snoyberg** [comment]
I've have 0 interest in writing or maintaining such a package. Anyone else
is welcome to do so of course.

**Comment by limick** [comment]
Thanks for the information, that helped.
For the record: I ended up changing some types from `fooConduit :: MonadThrow m => ConduitT i o m r`
to `fooConduit :: ConduitT i o IO r` and then at the call site replaced `barConduit .| fooConduit` by `barConduit .| transPipe liftIO fooConduit`.
