### ISSUE TITLE
Example of rendering CDATA

### ISSUE THREAD

**Issue by jezen** [snoyberg/xml#141]
Is there a way to wrap some values in CDATA for only a subset of an XML document? I can only find how to change the settings so that _every_ field has its contents wrapped in CDATA.

Alternatively, is there way to render an XML document inside another XML document?

Or another alternative: Is there something roughly equivalent to `preEscapedToMarkup`?

**Comment by snoyberg** [comment]
I'm not quite sure what your goal is here, or what layer of the API you're working at here. Perhaps a higher level question would make sense here.

**Comment by snoyberg** [comment]
Why do you need a CDATA?

**Comment by jezen** [comment]
> Why do you need a CDATA?

I’d like to dump a load of JSON inside an XML tag, and ideally for it to still be human-readable. As I understand it, without the CDATA some characters would need escaping. I expect these libraries handle escaping correctly, but that would mean the resulting JSON is slightly less human-readable.

Also, I may be using `rsUseCDATA` incorrectly — I’m giving it `const True`, which was taken from the only example I could find (which was in the test suite).

**Comment by snoyberg** [comment]
I don't think the library is designed to provide this kind of control, but
I could be wrong. I haven't played with this much in a long time.
