### ISSUE TITLE
html-conduit-1.3.2: Not in scope: ‘XML.parseText'’

### ISSUE THREAD

**Issue by juhp** [snoyberg/xml#148]
For Stackage Nightly:
```
   Building library for html-conduit-1.3.2..
    [1 of 2] Compiling Text.HTML.TagStream
    
    /var/stackage/work/unpack-dir/unpacked/html-conduit-1.3.2-4c409dc2ad34d07beb983a08907951cfadef549d221f9e8e6e074525085fa4c8/src/Text/HTML/TagStream.hs:152:14: error:
        Not in scope: ‘XML.parseText'’
        Perhaps you meant one of these:
          ‘XML.parseText’ (imported from Text.XML.Stream.Parse),
          ‘XML.parseTextPos’ (imported from Text.XML.Stream.Parse)
        Module ‘Text.XML.Stream.Parse’ does not export ‘parseText'’.
        |
    152 |           .| XML.parseText' XML.def { XML.psDecodeEntities = XML.decodeHtmlEntities }
        |              ^^^^^^^^^^^^^^
```

**Comment by k0ral** [comment]
This was fixed a while ago (cf [this commit][1]) as part of release 1.3.2.1, but it is unfortunately not published into [Hackage][2].
@snoyberg Could you please publish this release into Hackage, and add a `xml-conduit < 1.9` constraint on html-conduit 1.3.2 ?

[1]: https://github.com/snoyberg/xml/commit/930c9588654a9b93a858baaac99d5f02a04c1d0e
[2]: https://hackage.haskell.org/package/html-conduit

**Comment by snoyberg** [comment]
Upload made. The last upload seems to have failed and I didn't notice.
