### ISSUE TITLE
xml-picklers adds empty xmlns attribute to a non-namespaced element

### ISSUE THREAD

**Issue by l29ah** [snoyberg/xml#153]
Producing a "{}resource" element instead of a "resource" one. Curiously, if the parent element is not namespaced, it is rendered correctly.

Repro:
```
{-# LANGUAGE OverloadedStrings #-}

import Data.ByteString.Lazy as B
import Data.Either
import Data.Text
import Data.XML.Types
import qualified Text.XML as TX

main = B.putStr $ TX.renderLBS TX.def $ fromRight undefined $ TX.fromXMLDocument $ Document (Prologue [] Nothing []) (Element "{urn:ietf:params:xml:ns:xmpp-bind}bind" [] [NodeElement $ Element "resource" [] [NodeContent $ ContentText "test"]]) []
```
Result:
```
<?xml version="1.0" encoding="UTF-8"?><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource xmlns="">test</resource></bind>
```
Expected:
```
<?xml version="1.0" encoding="UTF-8"?><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>test</resource></bind>
```

**Comment by snoyberg** [comment]
Sounds correct to me. It needs to reset the inherited namespace.

**Comment by l29ah** [comment]
Okay, that makes sense, though completely non-intuitive that a Nothing namespace produces different XML depending on the context (non-namespaced if a parent, ""-namespaced if a child of a namespaced parent), and that the library compares provided namespace strings to decide whether the element need to be included.

**Comment by snoyberg** [comment]
That is the behavior of the XML namespace specification, not this library.
