### ISSUE TITLE
Newlines in text content removed

### ISSUE THREAD

**Issue by normenmueller** [snoyberg/xml#154]
in.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<model>
    <documentation>First line.
Second line.</documentation>
</model>
```

Exec:
```
main = do
    doc <- parse "./in.xml"
    txt <- pure . render' $ doc
    print txt
```

Out:
```
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<model xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n    <documentation>\n        First line. Second line.\n    </documentation>\n</model>\n"
                                                                                                                                                   ^^^^^^
```

with
```
parse = readFile dft
  where
    dft = def {psRetainNamespaces = True}

render' = renderText dft
  where
    dft = def {rsPretty = True, rsNamespaces = [("xsi", "http://www.w3.org/2001/XMLSchema-instance")]}
```

Any suggestion on how to retain those newlines in an element's text content?

**Comment by snoyberg** [comment]
I think this is intended to rsPretty being enabled

**Comment by normenmueller** [comment]
@snoyberg Don't want to start a discussion of principles, but shouldn't "prettyness" refer exclusively to the structure instead of the content?

Anyway, is there any workaround or would you have another recommendation for me?

**Comment by snoyberg** [comment]
My point is that pretty rendering inherently messes with whitespace. There's really no way around it. Even if it keeps the newlines, it will necessarily add spacing. I don't have a strong opinion on whether the newlines are kept or removed, but if retaining any kind of consistency in whitespace is your goal, you can't use pretty rendering. The rest are details that can change over time.

I'm not opposed to a PR that modifies the behavior of pretty rendering if it will help most people most of the time.
