### ISSUE TITLE
`]` character inside a comment inside DOCTYPE

### ISSUE THREAD

**Issue by jgm** [snoyberg/xml#157]
xml-conduit seems to break on this:

``` xml
<!DOCTYPE language SYSTEM "language.dtd" 
[ <!-- [hi there] -->                                          
  <!ENTITY gr_char_iso "[#$&amp;*+\-./:&lt;=>?@^~\\]">               
]> 
<language>                                
</language>                                 
```

Removing the `]` inside the `[hi there]` in the comment makes it work again.
I believe this is valid XML.

**Comment by k0ral** [comment]
Looking at [doctype specification](https://www.w3.org/TR/REC-xml/#NT-doctypedecl), I believe this is indeed valid XML. Thank you for contributing the fix !

**Comment by jgm** [comment]
Thanks.  Looking at the spec, it seems there are lots of other things besides comments that are allowed in doctypes that could potentially also contain closing brackets, e.g. `<!ELEMENT`, `<!NOTATION`, `<?` (PI).  It would be worth fixing all of these, to avoid similar problems in the future (though I don't anticipate them arising for my specific application).  And not too hard to do it right, I think.

**Comment by jgm** [comment]
I've added a new PR that should handle these cases as well.
