### ISSUE TITLE
The cabal-doctest library is deprecated

### ISSUE THREAD

**Issue by danwdart** [snoyberg/xml#170]
See: https://hackage.haskell.org/package/cabal-doctest
which references: https://github.com/haskell/cabal/issues/2327

Does this library still need it specifically? cabal-doctest blocks things from building on ghc 9.2.

**Comment by k0ral** [comment]
This library doesn't *need* it to work, it's just useful to guarantee that documentation examples are correct.
After reading the links you mentioned, and browsing the topic a little, it's not clear to me how we should achieve the same feature without `cabal-doctest` library.

Do you happen to know a working alternative ? If there aren't any, I guess we have 2 options:
1. wait for https://github.com/haskellari/cabal-doctest/pull/72 to get merged/released, then pull that release in `xml-conduit`
2. drop `cabal-doctest` dependency altogether
 
I'm opening https://github.com/snoyberg/xml/pull/171 right now, waiting for the outcome of 1/ to either close or merge it.

**Comment by k0ral** [comment]
I've upgraded `calab-doctest` dependency through https://github.com/snoyberg/xml/pull/174, which should be compatible with GHC 9.2 .
