### ISSUE TITLE
Cannot pass raw ampersand '&' to parseText

### ISSUE THREAD

**Issue by xave** [snoyberg/xml#182]
The objective is to give `parseText` a string "Apples & Oranges" without escaping the ampersand.

Using 

```
...parseText def {psDecodeIllegalCharacters=passAmpersand}
where
passAmpersand :: Int -> Maybe Char
passAmpersand = \case
38 -> Just '&'
_ -> Nothing
```

does not work because ampersand is not an illegal character, thus failing to trigger the `psDecodeIllegalCharacters`.

A potential workaround is to parse my string "Apples & Oranges" and replace it with something outside of the range such as `&#[0-9]+;` as in the docs for `psDecodeIllegalCharacters`.

1. I am unsure of how to represent `&#[0-9]+;` as an Int, where the output would be turned into `Just '&'`
2. It would be ideal to just say raw ampersand is fine instead of (1).

**Comment by k0ral** [comment]
Unless I am mistaken, `parseText` is designed to consume valid XML data, which the string `Apples & Oranges` is not. See [specification](https://www.w3.org/TR/xml/#syntax):
> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a [comment](https://www.w3.org/TR/xml/#dt-comment), a [processing instruction](https://www.w3.org/TR/xml/#dt-pi), or a [CDATA section](https://www.w3.org/TR/xml/#dt-cdsection). If they are needed elsewhere, they MUST be [escaped](https://www.w3.org/TR/xml/#dt-escape) using either [numeric character references](https://www.w3.org/TR/xml/#dt-charref) or the strings " &amp; " and " &lt; " respectively. 

It seems to me that what you want is a pre-processing function that escapes `&` (and other special characters) _before_ feeding the string to `parseText`. Example implementations (not type-checked, not tested):
- specific to `&`, less efficient:
  ```haskell
  import Data.Text (Text, replace) 

  escape :: Text -> Text
  escape = replace "&" "&amp;"
  ```
- applicable to all XML special characters, more efficient:
  ```haskell
  import Data.Default (def)
  import Data.XML.Types (Content(..), Event(..))
  import Text.XML.Stream.Render (renderText)
  
  escape :: (PrimMonad m, MonadThrow m) => Text -> ConduitT () Text m ()
  escape text = yield (EventContent $ ContentText text) .| renderText def
  ```

Does that fulfill your need ?

**Comment by xave** [comment]
It does. Thank you very much!
