### ISSUE TITLE
Parsing unordered elements

### ISSUE THREAD

**Issue by k0ral** [snoyberg/xml#51]
In many cases, one wants to parse a set of XML elements in whichever order they come. While the current `xml-conduit` API shines to parse ordered elements, it requires some efforts to be used with unordered ones.
Would you accept contributions to support this not-so-uncommon use case ? Also, do you have suggestions about the way to design/implement it ?

In the end, I'd like to be able to write something like:

``` haskell
-- New run-like functions, to choose which behavior to adopt
ordered = undefined
unordered = undefined

-- New consumer, inspired from 'ignoreAttrs'
ignoreElements = undefined

-- 1/ Parse <parentTag>, and some unordered children elements.
-- Fail if there is an unknown child.
tagName "parentTag" ignoreAttrs $ \_ -> unordered $ do
  child1 <- tagName "childTag1" ignoreAttrs (const content)
  -- ...
  childN <- tagName "childTagN" ignoreAttrs (const content)
  return $ Something child1 {- ... -} childN

-- 2/ Parse <parentTag>, and some unordered children elements.
-- Ignore unknown children.
tagName "parentTag" ignoreAttrs $ \_ -> unordered $ do
  child1 <- tagName "childTag1" ignoreAttrs (const content)
  -- ...
  childN <- tagName "childTagN" ignoreAttrs (const content)
  ignoreElements
  return $ Something child1 {- ... -} childN

-- 3/ Parse <parentTag>, and some ordered children elements.
tagName "parentTag" ignoreAttrs $ \_ -> ordered $ do
  child1 <- tagName "childTag1" ignoreAttrs (const content)
  -- ...
  childN <- tagName "childTagN" ignoreAttrs (const content)
  return $ Something child1 {- ... -} childN

-- This requires a change of the signature of 'tagName' (and many other functions)
```

**Comment by snoyberg** [comment]
I'm in favor of this change. A quick thought is that you'd probably want to use `Applicative` instead of `Monad` to make this happen, but that's about as deep as my thoughts on this go right now.

**Comment by k0ral** [comment]
I've just noticed Parsec has a [`Text.Parsec.Perm`][1] module for this exact feature, with an `Applicative`-like API.

[1]: https://hackage.haskell.org/package/parsec-3.1.9/docs/Text-Parsec-Perm.html

**Comment by k0ral** [comment]
Even better, the [`Text.Parser.Permutation`][1] module (from the `parsers` package) is a generalization of that trick for any instance of `Alternative`, which `ConduitM i o m` isn't. I resorted to some `MaybeT` wrapping to get the permutation parser feature without modifying `xml-conduit`:

```haskell
-- 'ConduitM i o m' is not an instance of 'Alternative'
-- so we need to run the parsers through 'MaybeT' (for example)
result <- runMaybeT . permute $ SomeConstructor
    <$?> (mempty, MaybeT (tagName "text" ignoreAttrs $ const content)) -- Text (optional)
    <||> MaybeT (tagName "text" ignoreAttrs $ const content) -- Text (mandatory)
    <|?> (Nothing, Just <$> MaybeT (tagName "date" ignoreAttrs . const $ parseTime =<< content)) -- Maybe UTCTime
    <|?> (Nothing, Just <$> MaybeT (tagName "uri" ignoreAttrs . const $ parseURI =<< content)) -- Maybe URI
```

The `MaybeT` wrapping is rather verbose, though. Maybe there's a way to provide some combinators to mitigate that.

[1]: https://hackage.haskell.org/package/parsers/docs/Text-Parser-Permutation.html

**Comment by k0ral** [comment]
Closing this issue as no longer relevant.
