### ISSUE TITLE
incorrect handling of iso8859-1

### ISSUE THREAD

**Issue by legrostdg** [snoyberg/xml#55]
When parsing an iso8859-1 html page, with the header

    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

the accentuated characters are rendered as �s.

Minimal example:

    {-# LANGUAGE OverloadedStrings #-}
    import Prelude hiding (readFile)
    import Network.HTTP.Conduit (simpleHttp)
    import qualified Data.Text.IO as TIO
    import Text.HTML.DOM (readFile)
    import Text.XML.Cursor

    url :: String
    url = "http://www.confederationpaysanne.fr/petites_annonces.php"

    main :: IO ()
    main = do
        cursor <- fromDocument `fmap` readFile file
        mapM_ TIO.putStrLn $ cursor $// element "title" &// content

**Comment by snoyberg** [comment]
This is probably coming from [tagstream-conduit](https://github.com/yihuang/tagstream-conduit) (pinging @yihuang). I don't know how feasible it is to support this workflow, though.

**Comment by yihuang** [comment]
Are we talking about `Text.HTML.TagStream.Text.tokenStreamBS` , and expect it to extract encoding from html meta tag?

**Comment by snoyberg** [comment]
I believe that's the request, except to extract it from the meta tag, not the XML declaration.

**Comment by snoyberg** [comment]
Closing, this is being tracked in the tagstream-conduit repo
