### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by s-trooper** [snoyberg/xml#59]
Hi for a simple dom parsing my program use 1.20 s, the same in F# (.net) 0.100 s. 10x slower :( Now the question as i am newbie in haskell, do i things wrong or it is as it is?

```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where
import qualified Text.XML as Xml
import           Formatting
import           Formatting.Clock
import           System.Clock

main :: IO ()
main = do
    start <- getTime Monotonic
    _ <- Xml.readFile Xml.def "..\\data\\file1.xml"
    end <- getTime Monotonic
    fprint ("parse_xml: " % timeSpecs % "\n") start end
```

```
parse_xml:      1.20 s
Execution time: 1.55 s
```

**Comment by snoyberg** [comment]
I can't see anything wrong with this snippet. xml-conduit has never been really optimised for speed, but 1.2 seconds seems very surprising. However, it's impossible to know what's going on without a lot more information:

* How did you compile the program?
* Did you pass in any runtime flags?
* What's the size of the XML file?

**Comment by s-trooper** [comment]
I use xml-conduit ==1.3.1 with GHC 7.10.1 and cabal config:
```
ghc-options:       -O2 -Wall -threaded -rtsopts -with-rtsopts=-N
```
No runtime flags or I am not aware of these, I use stack tool for build. It is a 3 MB Xml file.

btw.i tested  the hxt (Haskell XML Toolbox) and got **4.1s**! so xml-conduit is not that bad for Haskell ;) a comparison to MS .net may be not fair after all?

I am not able to say it is Haskell or xml-conduit issue so feel free to close or not this ticked as you like. i was just hoping that i misuse the lib.

**Comment by snoyberg** [comment]
I can't actually be certain what the C# version is doing to be honest, so it's difficult to make a comparison. But I can say that I have no plans on working on optimizations right now, so closing is likely the right thing. If you come up with any profiling information that points to a specific bottleneck, I'd be happy to work with you on improving performance.
