### ISSUE TITLE
Not in scope: data constructor ‘ParseSettings’

### ISSUE THREAD

**Issue by markmelling** [snoyberg/xml#62]
If I modify parser-sample.hs to provide a different ParseSettings, e.g.

````
let ps = ParseSettings { psDecodeEntities = decodeXmlEntities, psRetainNamespaces = True }
people <- runResourceT $
    parseFile ps "people.xml" $$ force "people required" parsePeople
````

I get 

````
Not in scope: data constructor ‘ParseSettings’
````

Is there something I'm doing wrong? or should ParseSettings be exported as ParseSettings(..)?

**Comment by snoyberg** [comment]
You're supposed to use `def { ... }` for updates. For more information, see:

http://www.yesodweb.com/book/settings-types

Reasoning: this syntax allows us to add new fields without making it a breaking change.

**Comment by markmelling** [comment]
OK thanks. And thanks for the super fast response!

**Comment by snoyberg** [comment]
No problem, you caught me during an email-answering binge ;)
