### ISSUE TITLE
xml-conduit fails to compile with HEAD

### ISSUE THREAD

**Issue by mpickering** [snoyberg/xml#71]
There is a bug in GHC which makes xml-conduit fail to compile with HEAD. [#11276](https://ghc.haskell.org/trac/ghc/ticket/11276) is the issue tracking the problem. 

A workaround is to add a type signature to `dropWS` which is a local definition in `pad` which is defined in the `Text.XML.Parse` module.

**Comment by k0ral** [comment]
Closing this issue as the mentioned GHC bug is marked as fixed.
Please let us know if you run into similar compilation failures.
