### ISSUE TITLE
Issues decoding leading escaped spaces when using Text.XML.Stream.Parse

### ISSUE THREAD

**Issue by alexkalderimis** [snoyberg/xml#74]
`content` and `maybeContent` both skip over leading escaped whitespace.

A minimal example is:
```xml
<term name="foo">&#160;&#39;&#160;</term>
```

where the content parses as: "'\160", rather than "\160'\160".

Note that trailing characters are treated correctly.

**Comment by alexkalderimis** [comment]
Note that I am having issues replicating this. I will report back here with any resolution.

**Comment by alexkalderimis** [comment]
Please see the attached PR: this is an issue with back-tracking. When choosing between an element or bare-content, the first character is stripped when it is encoded whitespace.

**Comment by snoyberg** [comment]
I've just pushed a commit to the whitespace branch which includes your test cases, which all now pass. Can you test this out before I merge/release?

**Comment by alexkalderimis** [comment]
Sorry, I somehow missed your message from the 15th of Feb. My apologies.
