### ISSUE TITLE
Parsing pretty printed XML results in whitespace

### ISSUE THREAD

**Issue by rubenmoor** [snoyberg/xml#77]
This behavior surprised me. When pretty-printing xml with xml-conduit, there is white space added, not only before and after tags but also around contents. Parsing this again, results in node contents with that whitespace.

Code [here](https://gist.github.com/rubenmoor/f5b0d78c57e3fdbe84d1)
Output:

    <?xml version="1.0" encoding="UTF-8"?>
    <foo>
        bar
    </foo>
    "\n    bar\n"

I would have expected a pretty printer that outputs `<foo>bar</foo>`, since "bar" is not a node. But the behavior seems intentional.
However, the parser output seems a logical consequence.

**Comment by snoyberg** [comment]
This is simply the way the pretty printer works, and there is no guarantee
of not getting extra whitespace in your output. It's why pretty printing is
off by default: it can change the semantics of your document.

**Comment by rubenmoor** [comment]
Alright. I don't want to do without pretty printing. So now, everywhere I use the `content` cursor, I put `Text.strip`.
