### ISSUE TITLE
Offer error mode that pretty prints and diffs XML documents

### ISSUE THREAD

**Issue by bitemyapp** [snoyberg/xml#78]
Currently figuring out what you did wrong is a pain, pretty printing and diffing "expected"/"actual" in a user's query into the document would help.

**Comment by snoyberg** [comment]
I don't know what this means, can you clarify?

**Comment by k0ral** [comment]
Closing this issue as it requires clarification but has been inactive for a while.
Don't hesitate to re-open it with requested clarification, if still relevant.
