### ISSUE TITLE
Example in Text.XML.Stream.Parse requires type signatures

### ISSUE THREAD

**Issue by ivan-m** [snoyberg/xml#99]
If I try and run the first example as-is, I get the following error:

```
ghc: panic! (the 'impossible' happened)
  (GHC version 8.0.2 for x86_64-apple-darwin):
	nameModule system $dShow_acbe
```

If, however, I add type signatures, then I get the expected result (though not as shown in the docs: the provided `People` type isn't a record type, but the printed result is).

**Comment by ivan-m** [comment]
More specifically: `parsePeople` needs a type signature, possibly due to the use of `Void` in `Sink`.

**Comment by k0ral** [comment]
I'm not having the issue with GHC 8.0.1 on x86_64-linux.
I'll add the type signatures anyway, if that can help.

**Comment by k0ral** [comment]
Done in cec8d19549500b0ef3b5128beb6c529758b1ee69 . Could you please confirm this is what you expected ?

**Comment by ivan-m** [comment]
I had it working with `Sink`, but yes, that seems to do the trick; ta!
